---

- hosts: all
  become: true
  tasks:


  - name: install apache2 and mod-php package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
