---

- hosts: all
  become: true
  tasks:


  - name: update repository index
    apt:
      update_cache: yes

  - name: install apache2 package
    apt:
      name: apache2
      state: absent

  - name: add php support for apche
    apt:
      name: libapache2-mod-php
      state: absent
